name: missionaire
favicon: null
layout_spectrum: 0.95375
typography_spectrum: 0.28394430060870945
title: 'Money poor, mission rich'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.44669629470445216
  lightness: 0.822931898990646
  saturation: 0.4020884505007416
  rhythmicContrast: 0.8072456398513168
purpose: []
