name: missionaire
favicon: null
layout_spectrum: 0.95375
typography_spectrum: 0.58444
title: 'Money poor, mission rich'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#523c2e'
    - '#191814'
    - '#ffffff'
    - '#bba494'
    - '#d2cec2'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
